# docker-compose automatically creates a network for all the services defined in the file,
# and each service can communicate with other services on that network by default
services:
  green_trip_database:
    image: postgres:13
    networks:
      - pg-network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - pg-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  networks:
    pg-network:
# commands

# docker-compose up -d
# -d flag is for detached mode, to run the containers in the background rather than enter the shell

# docker-compose down to stop the containers
